parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - prettier

rules:
  no-alert: "off"
  no-console: "off"
  global-require: "off"
  object-curly-newline: "off"

  react/react-in-jsx-scope: "off"
  react/require-default-props: "off"
  react/jsx-one-expression-per-line: "off"
  react/jsx-props-no-spreading: "off"

  prettier/prettier: warn
  import/prefer-default-export: "off"
  jsx-a11y/accessible-emoji: "off"
  "@typescript-eslint/no-non-null-assertion": off
