parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 12
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended

rules:
  react/react-in-jsx-scope: off
  react/prop-types: ["error", { "ignore": ["navigation"] }]
  no-alert: 0
  no-console: 0
  react/jsx-props-no-spreading: off
  global-require: 0
  object-curly-newline: 0
  react/require-default-props: off
  import/prefer-default-export: off