export default interface NewPost {
  account_id: number,
  account_url: string,
  ad_type: string | null,
  ad_url: string | null,
  animated: boolean,
  bandwidth: number,
  datetime: number,
  deletehash: string,
  description: string | null,
  favorite: boolean,
  has_sound: boolean,
  height: number,
  hls: string,
  id: string,
  in_gallery: boolean,
  in_most_viral: boolean,
  is_ad: boolean,
  link: string,
  mp4: string,
  name: string,
  nsfw: string | null,
  section: string | null,
  size: number,
  tags: [],
  title: string | null,
  type: string,
  views: number,
  vote: string | null,
  width: number,
}
