export default interface Settings {
  accepted_gallery_terms: boolean,
  account_url: string,
  active_emails: string[],
  album_privacy: string,
  avatar: string,
  blocked_users: string[],
  comment_replies: boolean,
  cover: string,
  email: string,
  first_party: boolean,
  messaging_enabled: boolean,
  newsletter_subscribed: boolean,
  pro_expiration: boolean,
  public_images: boolean,
  show_mature: boolean,
}
