name: Application CI

on:
  push:

jobs:
  Build :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies and build
      working-directory: ./
      run: |
        npm ci
        npm start
      env:
        CI: true

  Test :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies and test
      working-directory: ./
      run: |
        npm ci
        npm run test
      env:
        CI: true

  Lint :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies and launch linter
      working-directory: ./
      run: |
        npm ci
        npm run lint
      env:
        CI: true
